// FAKE DATA
export const books = [
    {
      id: 1,
      title: "Think and Grow Rich",
      url: "https://m.media-amazon.com/images/I/71UypkUjStL.jpg",
      originalPrice: 49.95,
      salePrice: 14.95,
      rating: 4.5,
    },
    {
      id: 2,
      title: "Atomic Habits",
      url: "https://m.media-amazon.com/images/I/81bGKUa1e0L.jpg",
      originalPrice: 39,
      salePrice: null,
      rating: 5,
    },
    {
      id: 3,
      title: "Can't Hurt Me",
      url: "https://m.media-amazon.com/images/I/81gTRv2HXrL._AC_UF1000,1000_QL80_.jpg",
      originalPrice: 29,
      salePrice: null,
      rating: 5,
    },
    {
      id: 4,
      title: "Deep Work",
      url: "https://m.media-amazon.com/images/I/417yjF+Z5zL.jpg",
      originalPrice: 44,
      salePrice: 19,
      rating: 4.5,
    },
    {
      id: 5,
      title: "The 10X Rule",
      url: "https://m.media-amazon.com/images/I/71hjq42hvGL.jpg",
      originalPrice: 32,
      salePrice: null,
      rating: 5,
    },
    {
      id: 6,
      title: "The 4-Hour Workweek",
      url: "https://m.media-amazon.com/images/I/81qW97ndkvL.jpg",
      originalPrice: 70,
      salePrice: 12.5,
      rating: 5,
    },
    {
      id: 7,
      title: "Rich Dad Poor Dad",
      url: "https://m.media-amazon.com/images/I/81bsw6fnUiL.jpg",
      originalPrice: 11,
      salePrice: 10,
      rating: 4,
    },
    {
      id: 8,
      title: "Principles",
      url: "https://m.media-amazon.com/images/I/61aug2ORFVL.jpg",
      originalPrice: 38,
      salePrice: 17.95,
      rating: 4.5,
    },
    {
      id: 9,
      title: "48 Laws of Power",
      url: "https://m.media-amazon.com/images/I/71aG+xDKSYL.jpg",
      originalPrice: 35,
      salePrice: 19.95,
      rating: 4.5,
    },
    {
      id: 10,
      title: "Ego Is The Enemy",
      url: "https://m.media-amazon.com/images/I/71YxVWjZP1L.jpg",
      originalPrice: 40,
      salePrice: null,
      rating: 5,
    },
    {
      id: 11,
      title: "How to Win Friends & Influence People",
      url: "https://m.media-amazon.com/images/I/71vK0WVQ4rL.jpg",
      originalPrice: 30,
      salePrice: 20,
      rating: 5,
    },
    {
      id: 12,
      title: "Mastery",
      url: "https://m.media-amazon.com/images/I/71LRdEUOmNL.jpg",
      originalPrice: 30,
      salePrice: 12.95,
      rating: 4.5,
    },
    {
      id: 13,
      title: "Never Split The Difference",
      url: "https://m.media-amazon.com/images/I/81oUPEIf6OL.jpg",
      originalPrice: 32,
      salePrice: null,
      rating: 4,
    },
    {
      id: 14,
      title: "Thinking, Fast and Slow",
      url: "https://m.media-amazon.com/images/I/61fdrEuPJwL.jpg",
      originalPrice: 10,
      salePrice: null,
      rating: 4,
    },
    {
      id: 15,
      title: "Japanese From Zero!",
      url: "https://m.media-amazon.com/images/I/71yv7q0Zj-L.jpg",
      originalPrice: 50,
      salePrice: 19.95,
      rating: 4,
    },
    {
      id: 16,
      title: "Never Finished",
      url: "https://m.media-amazon.com/images/I/81uWWAHp25L.jpg",
      originalPrice: 50,
      salePrice: null,
      rating: 5,
    }
  ];